const petCareItems = [
  {
    title: "Eco-Friendly Dog Chew Toy",
    image_url: "",
    alt_text: "",
    price: 12.99,
    stores: ["Petco", "Amazon", "Chewy"],
    animal: ["Dog"],
  },
  {
    title: "Self-Cleaning Litter Box",
    image_url: "",
    alt_text: "",
    price: 149.99,
    stores: ["Amazon", "Chewy", "PetSmart"],
    animal: ["Cat"],
  },
  {
    title: "Hamster Hideout House",
    image_url: "",
    alt_text: "",
    price: 8.99,
    stores: ["Petco", "Amazon"],
    animal: ["Hamster"],
  },
  {
    title: "Dental Chews for Dogs",
    image_url: "",
    alt_text: "",
    price: 9.99,
    stores: ["PetSmart", "Chewy", "Amazon"],
    animal: ["Dog"],
  },
  {
    title: "Catnip-Infused Play Ball",
    image_url: "",
    alt_text: "",
    price: 4.99,
    stores: ["Chewy", "Petco"],
    animal: ["Cat"],
  },
  {
    title: "Aquarium Cleaning Kit",
    image_url: "",
    alt_text: "",
    price: 19.99,
    stores: ["Amazon", "Petco"],
    animal: ["Fish"],
  },
  {
    title: "Organic Bird Seed Mix",
    image_url: "",
    alt_text: "",
    price: 14.99,
    stores: ["PetSmart", "Amazon"],
    animal: ["Bird"],
  },
  {
    title: "Pet First Aid Kit",
    image_url: "",
    alt_text: "",
    price: 24.99,
    stores: ["Amazon", "Chewy"],
    animal: ["Dog", "Cat", "Hamster", "Rabbit", "Bird"],
  },
  {
    title: "Dog Paw Balm",
    image_url: "",
    alt_text: "",
    price: 11.99,
    stores: ["Chewy", "PetSmart", "Amazon"],
    animal: ["Dog"],
  },
  {
    title: "Cat Climbing Tree",
    image_url: "",
    alt_text: "",
    price: 89.99,
    stores: ["Petco", "Amazon"],
    animal: ["Cat"],
  },
  {
    title: "Hamster Running Wheel",
    image_url: "",
    alt_text: "",
    price: 6.99,
    stores: ["Petco", "Chewy"],
    animal: ["Hamster"],
  },
  {
    title: "Aquarium LED Light",
    image_url: "",
    alt_text: "",
    price: 29.99,
    stores: ["Amazon", "PetSmart"],
    animal: ["Fish"],
  },
  {
    title: "Dog Training Treats",
    image_url: "",
    alt_text: "",
    price: 7.99,
    stores: ["Chewy", "Petco"],
    animal: ["Dog"],
  },
  {
    title: "Bird Bath Perch",
    image_url: "",
    alt_text: "",
    price: 5.99,
    stores: ["PetSmart", "Amazon"],
    animal: ["Bird"],
  },
  {
    title: "Heated Cat Bed",
    image_url: "",
    alt_text: "",
    price: 39.99,
    stores: ["Amazon", "Chewy"],
    animal: ["Cat"],
  },
  {
    title: "Automatic Fish Feeder",
    image_url: "",
    alt_text: "",
    price: 24.99,
    stores: ["PetSmart", "Amazon"],
    animal: ["Fish"],
  },
  {
    title: "Rabbit Chew Sticks",
    image_url: "",
    alt_text: "",
    price: 4.49,
    stores: ["Petco", "Amazon"],
    animal: ["Rabbit"],
  },
  {
    title: "Dog Cooling Vest",
    image_url: "",
    alt_text: "",
    price: 34.99,
    stores: ["Chewy", "Amazon"],
    animal: ["Dog"],
  },
  {
    title: "Bird Cuddle Swing",
    image_url: "",
    alt_text: "",
    price: 6.99,
    stores: ["PetSmart", "Chewy"],
    animal: ["Bird"],
  },
  {
    title: "Fish Tank Water Filter",
    image_url: "",
    alt_text: "",
    price: 12.99,
    stores: ["Amazon", "Petco"],
    animal: ["Fish"],
  },
];
